version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: quickdocs_db
    restart: always
    environment:
      # Usamos valores genéricos estándar de desarrollo local
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-development_pass}
      POSTGRES_DB: ${DB_NAME:-quickdocs_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: