version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: quickdocs_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tu_password_seguro
      POSTGRES_DB: quickdocs_v2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data: