// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuickDocs.Backend.Data;

#nullable disable

namespace QuickDocs.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518215507_ModelosAisladosPorUsuario")]
    partial class ModelosAisladosPorUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuickDocs.Core.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CuitCuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Localidad")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.DetallePresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<string>("DescripcionSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("numeric");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("DetallesPresupuesto");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.DetalleRemito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<string>("DescripcionSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioAplicado")
                        .HasColumnType("numeric");

                    b.Property<int>("RemitoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RemitoId");

                    b.ToTable("DetallesRemito");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminador")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NumeroCorrelativo")
                        .HasColumnType("integer");

                    b.Property<int>("PuntoEmision")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Documentos");

                    b.HasDiscriminator<string>("Discriminador").HasValue("Documento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CondicionIva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoSecundario")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.NotaCredito", b =>
                {
                    b.HasBaseType("QuickDocs.Core.Models.Documento");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("NotaCredito");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Presupuesto", b =>
                {
                    b.HasBaseType("QuickDocs.Core.Models.Documento");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.ToTable("Documentos", t =>
                        {
                            t.Property("Estado")
                                .HasColumnName("Presupuesto_Estado");

                            t.Property("FechaVencimiento")
                                .HasColumnName("Presupuesto_FechaVencimiento");

                            t.Property("Total")
                                .HasColumnName("Presupuesto_Total");
                        });

                    b.HasDiscriminator().HasValue("Presupuesto");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Recibo", b =>
                {
                    b.HasBaseType("QuickDocs.Core.Models.Documento");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FormaPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("ImporteRecibido")
                        .HasColumnType("numeric");

                    b.Property<int?>("RemitoId")
                        .HasColumnType("integer");

                    b.ToTable("Documentos", t =>
                        {
                            t.Property("Detalle")
                                .HasColumnName("Recibo_Detalle");
                        });

                    b.HasDiscriminator().HasValue("Recibo");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Remito", b =>
                {
                    b.HasBaseType("QuickDocs.Core.Models.Documento");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PresupuestoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.ToTable("Documentos", t =>
                        {
                            t.Property("Descuento")
                                .HasColumnName("Remito_Descuento");

                            t.Property("Estado")
                                .HasColumnName("Remito_Estado");

                            t.Property("Subtotal")
                                .HasColumnName("Remito_Subtotal");

                            t.Property("Total")
                                .HasColumnName("Remito_Total");
                        });

                    b.HasDiscriminator().HasValue("Remito");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Cliente", b =>
                {
                    b.HasOne("QuickDocs.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.DetallePresupuesto", b =>
                {
                    b.HasOne("QuickDocs.Core.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("QuickDocs.Core.Models.Presupuesto", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.DetalleRemito", b =>
                {
                    b.HasOne("QuickDocs.Core.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("QuickDocs.Core.Models.Remito", null)
                        .WithMany("Detalles")
                        .HasForeignKey("RemitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Documento", b =>
                {
                    b.HasOne("QuickDocs.Core.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("QuickDocs.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Item", b =>
                {
                    b.HasOne("QuickDocs.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Perfil", b =>
                {
                    b.HasOne("QuickDocs.Core.Models.Usuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("QuickDocs.Core.Models.Perfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Usuario", b =>
                {
                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Presupuesto", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("QuickDocs.Core.Models.Remito", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
